
version: "3"

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=argo
      - POSTGRES_USER=argo
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8081:8080

  redis:
    image: redis:alpine
    ports:
      - 6381:6379
