apiVersion: v1
stringData:
  APP_URL: {{ .Values.appUrl }}
  {{- with .Values.database }}
  DB_HOST: {{ .host | quote }}
  DB_PORT: {{ .port | quote }}
  DB_NAME: {{ .name | quote }}
  DB_USERNAME: {{ .username | quote }}
  DB_PASSWORD: {{ .password | quote }}
  {{- end }}
  {{- with .Values.redis }}
  REDIS_HOST: {{ .host | quote }}
  REDIS_PORT: {{ .port | quote }}
  {{- end }}
  {{- with .Values.crypto }}
  APP_IV: {{ .iv | quote }}
  APP_SECRET: {{ .secret | quote }}
  {{- end }}
  {{- with .Values.facebook }}
  FACEBOOK_ID: {{ .id | quote }}
  FACEBOOK_SECRET: {{ .secret | quote }}
  {{- end }}
  {{- with .Values.google }}
  GOOGLE_ID: {{ .id | quote }}
  GOOGLE_SECRET: {{ .secret | quote }}
  {{- end }}
kind: Secret
metadata:
  name: {{ include "oauth2.fullname" . }}-env
  labels:
  {{- include "oauth2.labels" . | nindent 4 }}
type: Opaque
